<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
	<title>Recept-api</title>
	<style>
		body {
			margin: 50px 0 0 0;
			padding: 0;
			width: 100%;
			font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
			font-size: 18px;
		}
		.wrap {
			margin: 5em auto 0;
			max-width: 40em;
		}
		input[type="text"] {
			width: 100%;
		}
	</style>
	<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<div class="wrap">
	<form class="pure-form pure-form-stacked" method="post" action="/recipes/new">
		<input type="text" name="title" placeholder="Title"/>
		<input type="text" name="description" placeholder="Description"/>
		<input type="text" name="ingredients[0][name]" placeholder="Ingredient"/>
		<input type="text" name="ingredients[0][value]" placeholder="Value"/>
		<input type="text" name="ingredients[0][unit]" placeholder="Unit"/>
		<input type="text" name="ingredients[1][name]" placeholder="Ingredient"/>
		<input type="text" name="ingredients[1][value]" placeholder="Value"/>
		<input type="text" name="ingredients[1][unit]" placeholder="Unit"/>
		<input type="submit" value="Send"/>
	</form>
</div>
</body>
</html>
